// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options1.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbV_jVqxmFoQjjonfm5BKyvZY49tu_2f0',
    appId: '1:627060700121:web:484c815c109576f1e99fc8',
    messagingSenderId: '627060700121',
    projectId: 'presenceapp-40ed9',
    authDomain: 'presenceapp-40ed9.firebaseapp.com',
    storageBucket: 'presenceapp-40ed9.appspot.com',
    measurementId: 'G-407LRYB2EV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdvuw6oEup21reAfn_N0eXobqWQ2W0ufM',
    appId: '1:627060700121:android:ac8f843395166b62e99fc8',
    messagingSenderId: '627060700121',
    projectId: 'presenceapp-40ed9',
    storageBucket: 'presenceapp-40ed9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHQ2IRf7J-gJllS0ZwKujjOlNO1a9iJEE',
    appId: '1:627060700121:ios:df70c25e123ba9a8e99fc8',
    messagingSenderId: '627060700121',
    projectId: 'presenceapp-40ed9',
    storageBucket: 'presenceapp-40ed9.appspot.com',
    iosClientId: '627060700121-iau5d5lnoqlv393cl61kmk8q49203rmc.apps.googleusercontent.com',
    iosBundleId: 'com.example.presenceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHQ2IRf7J-gJllS0ZwKujjOlNO1a9iJEE',
    appId: '1:627060700121:ios:2484c384d8fa5ecfe99fc8',
    messagingSenderId: '627060700121',
    projectId: 'presenceapp-40ed9',
    storageBucket: 'presenceapp-40ed9.appspot.com',
    iosClientId: '627060700121-mae1k2op2vesskn60pj6hja68d9u505a.apps.googleusercontent.com',
    iosBundleId: 'com.example.presenceApp.RunnerTests',
  );
}
