// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJfZJtZ43KALdAIGKJJ7bTPnL9wQsrq5w',
    appId: '1:201787268026:web:2519863707fc380cb25b83',
    messagingSenderId: '201787268026',
    projectId: 'myapp-fd370',
    authDomain: 'myapp-fd370.firebaseapp.com',
    databaseURL: 'https://myapp-fd370-default-rtdb.firebaseio.com',
    storageBucket: 'myapp-fd370.appspot.com',
    measurementId: 'G-NR81SX3M00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7CdRgyc1bEmQG2UYUPDavUP_IlqbktxY',
    appId: '1:201787268026:android:d330af2229359983b25b83',
    messagingSenderId: '201787268026',
    projectId: 'myapp-fd370',
    databaseURL: 'https://myapp-fd370-default-rtdb.firebaseio.com',
    storageBucket: 'myapp-fd370.appspot.com',
  );
}
